name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build webpack
        run: npm run build

      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-artifact
          path: out/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: built-artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy JS, CSS, Asset files to the S3 with the AWS CLI
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }} --cache-control "public, max-age=31536000" --exclude "*.html"

      - name: Copy oHTML files t the S3 with the AWS CLI
        run: aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }} --cache-control "no-cache"

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
