name: Deploy Fusuma Slides
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: node-cache
        env:
          cache-name: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build slides
        run: npm run build:slide

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy slide assets(CSS, JS, images, etc.) to S3
        run: aws sync ./dist s3://github-action-aws-s3-cloudfront-seminar-slides.eunsukim.me --cache-control "public, max-age=31536000" --exclude "*.html"

      - name: Deploy slide HTML to S3
        run: aws sync ./dist s3://github-action-aws-s3-cloudfront-seminar-slides.eunsukim.me --cache-control "no-cache"
